# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5230:5230
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
